import { BehaviourEvents, BehaviourItems, CaptchaLanguage, CaptchaText, ClientInfo, PreferedTheme } from "./types";
export declare const behaviourInit: BehaviourItems;
export declare const clientInfoInit: ClientInfo;
export declare const canvasFonts: string[];
export declare const abcLowerCase = "abcdefghijklmnopqrstuvwxyz";
export declare const abcUpperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export declare const numbers = "0123456789";
export declare const abc123Complete: string;
export declare const abcComplete: string;
export declare const abc123Friendly = "ABCDEFGHJKMNPQRTUWXYZabcdefghijkmnpqrtwxyz0123456789";
export declare const USER_INPUT_EVENTS: Record<string, BehaviourEvents>;
export declare const CAPTCHA_DEFAULTS: Readonly<{
    STRING_MIN_LENGTH: 4;
    STRING_MAX_LENGTH: 6;
    TIME_BEFORE_INPUTS: 2000;
    MAX_ATTEMPTS: 10;
    PREFERED_THEME: PreferedTheme;
    LANGAUGE: CaptchaLanguage;
    USE_STYLE_SHEET: true;
}>;
export declare const CAPTCHA_TEXTS: CaptchaText;
